### ISSUE TITLE
Proxy chain convention not implement

### ISSUE THREAD

**Issue by Soneoylys** [xmdhs/clash2singbox#16]
Proxy daisy chain not implement.
没有实现链式代理转换, 以下是脱敏后的原始Clash配置文件:

```
log-level: error
mode: rule
ipv6: true
unified-delay: true
tcp-concurrent: true
allow-lan: true
bind-address: "*"
mixed-port: 57890
external-controller: 127.0.0.1:59090
global-client-fingerprint: safari
global-ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15"

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:5****
  enhanced-mode: fake-ip
  fake-ip-range: 10.10.255.1/24
  fake-ip-filter: ['stun.*.*.*', 'stun.*.*']
  default-nameserver: [1.1.1.1, 8.8.8.8, '2606:4700:4700::1111', '2001:4860:4860::8888']
  nameserver: [https://dns.opendns.com/dns-query, https://dns10.quad9.net/dns-query]
  proxy-server-nameserver: [https://dns.k******.net/dns-query, https://gateway.k******.net/dns-query]

rules:
  - MATCH,SELECT-HERE(Global)

proxy-groups:
  # DEFINE PROXYCHAIN
  - { name: SELECT-HERE(Global), type: select, url: 'http://cp.cloudflare.com', proxies: [US, JP] }
  - { name: NO "Direct" IN CHINA, type: select, proxies: [REJECTME] }
  - { name: -------IGNORE BELOW-------, type: relay, hidden: true, proxies: [REJECTME] }
  - { name: US, type: relay, hidden: true, proxies: [A-SDWAN, Direct-US] }
  - { name: JP, type: relay, hidden: true, proxies: [B-SDWAN, Direct-JP] } # Symmetric NAT

proxies:
  # DEFINE REJECT
  - { name: REJECTME, type: ss, server: localhost, port: 8388, cipher: aes-256-cfb, password: Barfoo!, udp: false, ip-version: ipv4 }
  # DEFINE SDWAN
  - { name: A-SDWAN, type: ss, server: sdwan1.k******.net, port: 1****, cipher: chacha20-ietf-poly1305, password: c*****, udp: true, udp-over-tcp: true, udp-over-tcp-version: 1, ip-version: ipv4 }
  - { name: B-SDWAN, type: ss, server: sdwan2.k******.net, port: 1****, cipher: chacha20-ietf-poly1305, password: c*****, udp: true, udp-over-tcp: true, udp-over-tcp-version: 1, ip-version: ipv4 }
  # DEFINE DIRECT
  - { name: Direct-US, server: us1.k******.net, port: 6****, type: ss, cipher: aes-256-gcm, password: K******, udp: true, ip-version: ipv4 }
  - { name: Direct-JP, server: jp1.k******.net, port: 6****, type: ss, cipher: aes-256-gcm, password: K******, udp: true, ip-version: ipv6 }
```
