### ISSUE TITLE
SSR类型的节点在转换时，会漏掉protocol字段

### ISSUE THREAD

**Issue by deuteros-gex** [xmdhs/clash2singbox#2]
感谢作者提供的这个项目

比如clash配置文件中有这么一个ssr节点
```
proxies:
  - name: HK-SSR
    server: this.is.a.server
    port: 15000
    type: ssr
    cipher: aes-256-cfb
    password: ThisIsPassword
    protocol: auth_aes128_sha1
    obfs: http_simple
    protocol-param: password
    obfs-param: download.windowsupdate.com
    udp: true
```
转换过后会变成
```
        {
            "password": "ThisIsPassword",
            "server": "this.is.a.server",
            "server_port": 15000,
            "tag": "HK-SSR",
            "type": "shadowsocksr",
            "method": "aes-256-cfb",
            "obfs": "http_simple",
            "obfs_param": "download.windowsupdate.com",
            "protocol_param": "password"
        }
```
漏掉了一行`"protocol": "auth_aes128_sha1"`
测过本地编译的二进制和作者提供的在线转换网站，都是一样的结果，应该不是我操作问题
